#!/usr/bin/env python3
"""Regression tests for review-upload path containment."""

from __future__ import annotations

import asyncio
import io
import sys
import tempfile
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1] / "app"
sys.path.insert(0, str(APP_DIR))

from fastapi import UploadFile

import server


fails = []


def check(label, condition, detail=None):
    if condition:
        print(f"  PASS  {label}")
    else:
        print(f"  FAIL  {label}")
        if detail is not None:
            print(f"        {detail}")
        fails.append(label)


class FakeThread:
    """Capture review-thread arguments without executing the review."""

    calls = []

    def __init__(self, *, target, args, daemon):
        self.target = target
        self.args = args
        self.daemon = daemon
        self.__class__.calls.append(self)

    def start(self):
        pass


original_mkdtemp = server.tempfile.mkdtemp
original_thread = server.threading.Thread


with tempfile.TemporaryDirectory() as root:
    root = Path(root)
    upload_dir = root / "review_tmp"
    upload_dir.mkdir()

    def fake_mkdtemp(*, prefix):
        return str(upload_dir)

    try:
        server.tempfile.mkdtemp = fake_mkdtemp
        server.threading.Thread = FakeThread

        cases = [
            ("parent traversal", "../escaped.pdf"),
            ("absolute path", str(root / "absolute.pdf")),
        ]

        for label, supplied_name in cases:
            print(f"\n[{label}]")
            FakeThread.calls.clear()

            upload = UploadFile(
                filename=supplied_name,
                file=io.BytesIO(b"synthetic manuscript"),
            )

            result = asyncio.run(
                server.start_review(
                    file=upload,
                    domain="general",
                    thinking="",
                    vision="",
                )
            )

            check(
                "review accepted",
                result.get("status") == "running",
                result,
            )

            check(
                "one background review prepared",
                len(FakeThread.calls) == 1,
                len(FakeThread.calls),
            )

            if FakeThread.calls:
                file_path = Path(FakeThread.calls[0].args[1])
                resolved_file = file_path.resolve()
                resolved_upload_dir = upload_dir.resolve()

                try:
                    resolved_file.relative_to(resolved_upload_dir)
                    contained = True
                except ValueError:
                    contained = False

                check(
                    "stored upload path remains inside server temp directory",
                    contained,
                    f"supplied={supplied_name!r}, destination={file_path}",
                )

                check(
                    "stored basename is generated by the application",
                    file_path.name == "upload.pdf",
                    f"supplied={supplied_name!r}, stored={file_path.name!r}",
                )

                check(
                    "supplied filename is retained as metadata",
                    server.review_jobs[result["job_id"]]["filename"]
                    == supplied_name,
                    server.review_jobs[result["job_id"]]["filename"],
                )

                server.review_jobs.pop(result["job_id"], None)

    finally:
        server.tempfile.mkdtemp = original_mkdtemp
        server.threading.Thread = original_thread


# ---------------------------------------------------------------------------
# File-type and size boundaries
# ---------------------------------------------------------------------------

with tempfile.TemporaryDirectory() as boundary_root:
    boundary_root = Path(boundary_root)

    original_mkdtemp = server.tempfile.mkdtemp
    original_thread = server.threading.Thread
    original_max_upload = getattr(server, "MAX_REVIEW_UPLOAD_BYTES", None)
    had_max_upload = hasattr(server, "MAX_REVIEW_UPLOAD_BYTES")

    created_dirs = []

    def boundary_mkdtemp(*, prefix):
        nonlocal_holder = boundary_mkdtemp
        path = boundary_root / f"tmp_{nonlocal_holder.next_number}"
        nonlocal_holder.next_number += 1
        path.mkdir()
        created_dirs.append(path)
        return str(path)

    boundary_mkdtemp.next_number = 0

    try:
        server.tempfile.mkdtemp = boundary_mkdtemp
        server.threading.Thread = FakeThread

        print("\n[unsupported file type is rejected before temp storage]")
        FakeThread.calls.clear()
        created_dirs.clear()

        upload = UploadFile(
            filename="manuscript.exe",
            file=io.BytesIO(b"not a manuscript"),
        )

        status = None
        try:
            asyncio.run(
                server.start_review(
                    file=upload,
                    domain="general",
                    thinking="",
                    vision="",
                )
            )
        except Exception as exc:
            status = getattr(exc, "status_code", None)

        check(
            "unsupported suffix is rejected with 400",
            status == 400,
            f"status={status}",
        )
        check(
            "unsupported suffix creates no temp directory",
            created_dirs == [],
            [str(p) for p in created_dirs],
        )
        check(
            "unsupported suffix starts no review thread",
            FakeThread.calls == [],
            len(FakeThread.calls),
        )

        print("\n[missing file extension is rejected]")
        FakeThread.calls.clear()
        created_dirs.clear()

        upload = UploadFile(
            filename="manuscript",
            file=io.BytesIO(b"not dispatchable"),
        )

        status = None
        try:
            asyncio.run(
                server.start_review(
                    file=upload,
                    domain="general",
                    thinking="",
                    vision="",
                )
            )
        except Exception as exc:
            status = getattr(exc, "status_code", None)

        check(
            "missing suffix is rejected with 400",
            status == 400,
            f"status={status}",
        )
        check(
            "missing suffix creates no temp directory",
            created_dirs == [],
            [str(p) for p in created_dirs],
        )
        check(
            "missing suffix starts no review thread",
            FakeThread.calls == [],
            len(FakeThread.calls),
        )

        print("\n[oversized upload is stopped and cleaned up]")
        FakeThread.calls.clear()
        created_dirs.clear()

        # Tiny limit keeps this regression test cheap. Production will use a
        # substantially larger constant.
        server.MAX_REVIEW_UPLOAD_BYTES = 16

        upload = UploadFile(
            filename="large.pdf",
            file=io.BytesIO(b"x" * 17),
        )

        status = None
        try:
            asyncio.run(
                server.start_review(
                    file=upload,
                    domain="general",
                    thinking="",
                    vision="",
                )
            )
        except Exception as exc:
            status = getattr(exc, "status_code", None)

        check(
            "oversized upload is rejected with 413",
            status == 413,
            f"status={status}",
        )
        check(
            "oversized upload starts no review thread",
            FakeThread.calls == [],
            len(FakeThread.calls),
        )
        check(
            "oversized upload created storage before size was known",
            len(created_dirs) == 1,
            [str(p) for p in created_dirs],
        )
        check(
            "oversized partial upload and temp directory are removed",
            len(created_dirs) == 1 and not created_dirs[0].exists(),
            [str(p) for p in created_dirs],
        )

    finally:
        server.tempfile.mkdtemp = original_mkdtemp
        server.threading.Thread = original_thread

        if had_max_upload:
            server.MAX_REVIEW_UPLOAD_BYTES = original_max_upload
        else:
            try:
                del server.MAX_REVIEW_UPLOAD_BYTES
            except AttributeError:
                pass


if fails:
    print(f"\nFAILED: {len(fails)} check(s)")
    raise SystemExit(1)

print("\nPASS: review uploads are contained, type-checked, size-bounded, and cleaned up")
