#!/usr/bin/env python3
"""Regression tests for review-upload path containment."""

from __future__ import annotations

import asyncio
import io
import sys
import tempfile
from pathlib import Path

APP_DIR = Path(__file__).resolve().parents[1] / "app"
sys.path.insert(0, str(APP_DIR))

from fastapi import UploadFile

import server


fails = []


def check(label, condition, detail=None):
    if condition:
        print(f"  PASS  {label}")
    else:
        print(f"  FAIL  {label}")
        if detail is not None:
            print(f"        {detail}")
        fails.append(label)


class FakeThread:
    """Capture review-thread arguments without executing the review."""

    calls = []

    def __init__(self, *, target, args, daemon):
        self.target = target
        self.args = args
        self.daemon = daemon
        self.__class__.calls.append(self)

    def start(self):
        pass


original_mkdtemp = server.tempfile.mkdtemp
original_thread = server.threading.Thread


with tempfile.TemporaryDirectory() as root:
    root = Path(root)
    upload_dir = root / "review_tmp"
    upload_dir.mkdir()

    def fake_mkdtemp(*, prefix):
        return str(upload_dir)

    try:
        server.tempfile.mkdtemp = fake_mkdtemp
        server.threading.Thread = FakeThread

        cases = [
            ("parent traversal", "../escaped.pdf"),
            ("absolute path", str(root / "absolute.pdf")),
        ]

        for label, supplied_name in cases:
            print(f"\n[{label}]")
            FakeThread.calls.clear()

            upload = UploadFile(
                filename=supplied_name,
                file=io.BytesIO(b"synthetic manuscript"),
            )

            result = asyncio.run(
                server.start_review(
                    file=upload,
                    domain="general",
                    thinking="",
                    vision="",
                )
            )

            check(
                "review accepted",
                result.get("status") == "running",
                result,
            )

            check(
                "one background review prepared",
                len(FakeThread.calls) == 1,
                len(FakeThread.calls),
            )

            if FakeThread.calls:
                file_path = Path(FakeThread.calls[0].args[1])
                resolved_file = file_path.resolve()
                resolved_upload_dir = upload_dir.resolve()

                try:
                    resolved_file.relative_to(resolved_upload_dir)
                    contained = True
                except ValueError:
                    contained = False

                check(
                    "stored upload path remains inside server temp directory",
                    contained,
                    f"supplied={supplied_name!r}, destination={file_path}",
                )

                check(
                    "stored basename is generated by the application",
                    file_path.name == "upload.pdf",
                    f"supplied={supplied_name!r}, stored={file_path.name!r}",
                )

                check(
                    "supplied filename is retained as metadata",
                    server.review_jobs[result["job_id"]]["filename"]
                    == supplied_name,
                    server.review_jobs[result["job_id"]]["filename"],
                )

                server.review_jobs.pop(result["job_id"], None)

    finally:
        server.tempfile.mkdtemp = original_mkdtemp
        server.threading.Thread = original_thread


if fails:
    print(f"\nFAILED: {len(fails)} check(s)")
    raise SystemExit(1)

print("\nPASS: upload paths are application-controlled and contained")
